import { useState, useEffect } from 'react'
import CompetitorScannerSection from './CompetitorScannerSection'
import {
    TrendingUpIcon, SearchIcon, TargetIcon, CalendarIcon, RocketIcon, UsersIcon,
    SeoIcon, MicIcon, GlobeIcon, PencilIcon, BoltIcon, MailIcon, PaletteIcon,
    TrendingDownIcon, BarChartIcon, MegaphoneIcon, ConstructionIcon, SparklesIcon,
    ChatBotIcon, ClockIcon, StarIcon, ArrowRightIcon, CheckIcon, FlameIcon
} from '../Icons'

// Map tool IDs to icons for consistent rendering
const TOOL_ICONS = {
    report: <TrendingUpIcon size={22} />,
    competitor: <SearchIcon size={22} />,
    marketing: <TargetIcon size={22} />,
    calendar: <CalendarIcon size={22} />,
    campaign: <RocketIcon size={22} />,
    personas: <UsersIcon size={22} />,
    seo: <SeoIcon size={22} />,
    brandvoice: <MicIcon size={22} />,
    websitecopy: <GlobeIcon size={22} />,
    adcopy: <PencilIcon size={22} />,
    social: <BarChartIcon size={22} />,
    email: <MailIcon size={22} />,
    design: <PaletteIcon size={22} />,
    automations: <BoltIcon size={22} />,
    analytics: <TrendingDownIcon size={22} />,
}

function Dashboard({ userData, onNavigate, linkedGenerationState, onLinkedGeneration }) {
    const [isLoaded, setIsLoaded] = useState(false)
    const [stats] = useState({
        totalGenerations: 47,
        activeAutomations: 3,
        creditsUsed: 2500,
        creditsTotal: 5000
    })

    useEffect(() => {
        setTimeout(() => setIsLoaded(true), 100)
    }, [])

    const { loading: linkedLoading, generated: linkedGenerated } = linkedGenerationState || { loading: false, generated: false }

    // Auto-generated reports (View Report immediately available)
    const autoGeneratedReports = [
        {
            id: 'report',
            title: 'Market Research',
            description: 'Industry analysis, market trends, opportunities & competitive landscape',
            time: '~3 min',
            credits: 150,
            popularity: 'Essential',
            uses: '3.1k',
            rating: 4.9,
            tags: ['Research', 'Data'],
            onView: () => onNavigate('report')
        },
        {
            id: 'competitor',
            title: 'Competitor Analysis',
            description: 'Deep competitive intelligence with SWOT analysis & strategic recommendations',
            time: '~4 min',
            credits: 175,
            uses: '2.2k',
            rating: 4.8,
            tags: ['Competition', 'SWOT'],
            onView: () => onNavigate('competitor')
        }
    ]

    // Linked reports with DIFFERENTIATED button colors
    const linkedReports = [
        {
            id: 'marketing',
            title: 'Marketing Plan',
            description: 'Complete marketing strategy tailored to your business goals and target audience',
            time: '~5 min',
            credits: 200,
            badge: 'most-popular',
            badgeText: 'MOST POPULAR',
            uses: '2.4k',
            rating: 4.9,
            tags: ['Strategy', 'Planning'],
            viewText: 'View Marketing Plan',
            buttonColor: 'purple',
            onView: () => onNavigate('marketing')
        },
        {
            id: 'calendar',
            title: 'Content Calendar',
            description: '30-day content plan with ready-to-post content for all your channels',
            time: '~3 min',
            credits: 150,
            badge: 'hot',
            badgeText: 'HOT',
            uses: '2.8k',
            rating: 4.9,
            tags: ['Content', 'Planning'],
            viewText: 'View Content Calendar',
            buttonColor: 'blue',
            onView: () => onNavigate('calendar')
        }
    ]

    // Other tools
    const strategyTools = [
        {
            id: 'campaign',
            title: 'Campaign Strategy',
            description: 'Full campaign blueprint with phases, KPIs, budget allocation & timeline',
            time: '~5 min',
            credits: 200,
            popularity: 'Trending',
            uses: '1.8k',
            rating: 4.8,
            tags: ['Campaigns', 'KPIs']
        },
        {
            id: 'personas',
            title: 'Buyer Personas',
            description: 'Detailed ideal customer profiles with demographics, psychographics & behavior',
            time: '~4 min',
            credits: 150,
            uses: '1.2k',
            rating: 4.7,
            tags: ['Audience', 'Research']
        },
    ]

    const researchTools = [
        {
            id: 'seo',
            title: 'SEO Strategy',
            description: 'Complete SEO roadmap with keywords, content plan & link building strategy',
            time: '~5 min',
            credits: 200,
            uses: '1.5k',
            rating: 4.7,
            tags: ['SEO', 'Keywords']
        },
    ]

    const contentTools = [
        {
            id: 'brandvoice',
            title: 'Brand Voice Guide',
            description: 'Define your unique brand personality, tone of voice & messaging guidelines',
            time: '~4 min',
            credits: 150,
            uses: '980',
            rating: 4.6,
            tags: ['Branding', 'Voice']
        },
        {
            id: 'websitecopy',
            title: 'Website Copy',
            description: 'High-converting landing page copy, headlines, CTAs & website content',
            time: '~4 min',
            credits: 150,
            uses: '1.4k',
            rating: 4.7,
            tags: ['Copy', 'Conversion']
        },
    ]

    const adTools = [
        {
            id: 'adcopy',
            title: 'Ad Copy Machine',
            description: 'High-converting ad copy for Facebook, Google, LinkedIn & more platforms',
            time: '~2 min',
            credits: 100,
            popularity: 'Fast',
            uses: '4.2k',
            rating: 4.9,
            tags: ['Ads', 'Copy']
        },
        {
            id: 'social',
            title: 'Social Scripts',
            description: "Engaging social media posts optimized for each platform's algorithm",
            time: '~3 min',
            credits: 125,
            uses: '3.5k',
            rating: 4.8,
            tags: ['Social', 'Posts']
        },
        {
            id: 'email',
            title: 'Email Sequences',
            description: 'Automated nurture & conversion email sequences that drive results',
            time: '~5 min',
            credits: 175,
            uses: '1.9k',
            rating: 4.7,
            tags: ['Email', 'Automation']
        },
    ]

    const comingSoon = [
        { id: 'design', title: 'Design Assets', description: 'AI-generated visual content & brand assets', eta: 'Q1 2025' },
        { id: 'automations', title: 'AI Workflows', description: 'Automated marketing workflows & triggers', eta: 'Q1 2025' },
        { id: 'analytics', title: 'Analytics', description: 'Performance tracking & actionable insights', eta: 'Q2 2025' },
    ]

    // Auto-generated card (View Report button)
    const renderAutoGeneratedCard = (report, index) => (
        <button
            key={report.id}
            className={`premium-card premium-card-clickable ${isLoaded ? 'card-loaded' : ''}`}
            onClick={report.onView}
            style={{ animationDelay: `${index * 80}ms` }}
        >
            {report.popularity && (
                <span className="premium-badge premium-badge-essential">{report.popularity}</span>
            )}
            <div className="premium-card-header">
                <div className="premium-icon-wrap">
                    <span className="premium-icon">{TOOL_ICONS[report.id]}</span>
                </div>
                <div className="premium-rating">
                    <span className="star-icon"><StarIcon /></span>
                    <span>{report.rating}</span>
                </div>
            </div>
            <div className="premium-card-body">
                <h3 className="premium-title">{report.title}</h3>
                <p className="premium-desc">{report.description}</p>
                <div className="premium-tags">
                    {report.tags.map(tag => (
                        <span key={tag} className="premium-tag">{tag}</span>
                    ))}
                </div>
            </div>
            <div className="premium-card-footer">
                <div className="premium-stats">
                    <span className="premium-stat"><span className="stat-icon"><ClockIcon /></span> {report.time}</span>
                    <span className="premium-stat"><span className="stat-icon stat-amber"><BoltIcon size={14} /></span> {report.credits}</span>
                    <span className="premium-stat"><span className="stat-icon stat-blue"><UsersIcon size={14} /></span> {report.uses}</span>
                </div>
                <span className="btn-view-emerald">
                    <span className="btn-icon"><TargetIcon size={14} /></span>
                    <span>View Report</span>
                    <span className="btn-arrow"><ArrowRightIcon /></span>
                </span>
            </div>
        </button>
    )

    // Linked card with DIFFERENTIATED colors
    const renderLinkedCard = (report, index) => {
        const colorClass = report.buttonColor === 'purple' ? 'purple' : 'blue'

        return (
            <div
                key={report.id}
                className={`premium-card premium-card-strategy premium-card-${colorClass} ${isLoaded ? 'card-loaded' : ''}`}
                style={{ animationDelay: `${index * 80}ms` }}
            >
                {/* Animated hover background */}
                <div className={`premium-card-glow premium-card-glow-${colorClass}`}></div>

                {/* Badge */}
                {report.badge && (
                    <span className={`premium-badge premium-badge-${report.badge}`}>
                        {report.badge === 'hot' && <span className="badge-flame"><FlameIcon /></span>}
                        {report.badgeText}
                    </span>
                )}

                <div className="premium-card-content">
                    <div className="premium-card-header">
                        <div className={`premium-icon-wrap premium-icon-${colorClass}`}>
                            <span className="premium-icon">{TOOL_ICONS[report.id]}</span>
                        </div>
                        <div className="premium-rating">
                            <span className="star-icon"><StarIcon /></span>
                            <span>{report.rating}</span>
                        </div>
                    </div>

                    <div className="premium-card-body">
                        <h3 className="premium-title">{report.title}</h3>
                        <p className="premium-desc">{report.description}</p>
                        <div className={`premium-tags premium-tags-${colorClass}`}>
                            {report.tags.map(tag => (
                                <span key={tag} className="premium-tag">{tag}</span>
                            ))}
                        </div>
                    </div>

                    <div className="premium-card-footer">
                        <div className="premium-stats">
                            <span className="premium-stat"><span className="stat-icon"><ClockIcon /></span> {report.time}</span>
                            <span className="premium-stat"><span className="stat-icon stat-amber"><BoltIcon size={14} /></span> {report.credits}</span>
                            <span className="premium-stat"><span className="stat-icon stat-blue"><UsersIcon size={14} /></span> {report.uses}</span>
                        </div>

                        {/* Button States */}
                        <div className="premium-btn-container">
                            {linkedLoading ? (
                                <button className={`btn-loading btn-loading-${colorClass}`} disabled>
                                    <span className="btn-spinner"></span>
                                    <span>Generating...</span>
                                </button>
                            ) : linkedGenerated ? (
                                <button className="btn-view-emerald" onClick={report.onView}>
                                    <span className="btn-icon">{TOOL_ICONS[report.id]}</span>
                                    <span>{report.viewText}</span>
                                    <span className="btn-arrow"><ArrowRightIcon /></span>
                                </button>
                            ) : (
                                <button
                                    className={`btn-generate-premium btn-generate-${colorClass}`}
                                    onClick={onLinkedGeneration}
                                >
                                    <span className="btn-icon"><SparklesIcon size={14} /></span>
                                    <span>Generate</span>
                                    <span className="btn-arrow"><ArrowRightIcon /></span>
                                </button>
                            )}
                        </div>
                    </div>
                </div>
            </div>
        )
    }

    // Standard generator card
    const renderGeneratorCard = (generator, index, sectionIndex) => (
        <button
            key={generator.id}
            className={`premium-card premium-card-clickable ${isLoaded ? 'card-loaded' : ''}`}
            onClick={() => onNavigate(generator.id)}
            style={{ animationDelay: `${(sectionIndex * 100) + (index * 80)}ms` }}
        >
            {generator.popularity && (
                <span className={`premium-badge premium-badge-${generator.popularity.toLowerCase()}`}>
                    {generator.popularity}
                </span>
            )}
            <div className="premium-card-header">
                <div className="premium-icon-wrap">
                    <span className="premium-icon">{TOOL_ICONS[generator.id]}</span>
                </div>
                <div className="premium-rating">
                    <span className="star-icon"><StarIcon /></span>
                    <span>{generator.rating}</span>
                </div>
            </div>
            <div className="premium-card-body">
                <h3 className="premium-title">{generator.title}</h3>
                <p className="premium-desc">{generator.description}</p>
                <div className="premium-tags">
                    {generator.tags.map(tag => (
                        <span key={tag} className="premium-tag">{tag}</span>
                    ))}
                </div>
            </div>
            <div className="premium-card-footer">
                <div className="premium-stats">
                    <span className="premium-stat"><span className="stat-icon"><ClockIcon /></span> {generator.time}</span>
                    <span className="premium-stat"><span className="stat-icon stat-amber"><BoltIcon size={14} /></span> {generator.credits}</span>
                    <span className="premium-stat"><span className="stat-icon stat-blue"><UsersIcon size={14} /></span> {generator.uses}</span>
                </div>
                <span className="btn-generate-simple">
                    <span>Generate</span>
                    <span className="btn-arrow"><ArrowRightIcon /></span>
                </span>
            </div>
        </button>
    )

    return (
        <div className={`dashboard-premium ${isLoaded ? 'dashboard-loaded' : ''}`}>
            {/* Hero Header */}
            <header className="dashboard-hero">
                <div className="dashboard-hero-bg"></div>
                <div className="dashboard-hero-content">
                    <div className="dashboard-hero-text">
                        <span className="dashboard-welcome-badge"><SparklesIcon size={14} /> Welcome back</span>
                        <h1 className="dashboard-hero-title">Marketing Command Center</h1>
                        <p className="dashboard-hero-subtitle">
                            Choose from 12 AI-powered generators to create professional marketing assets in minutes.
                        </p>
                    </div>
                    <div className="dashboard-hero-stats">
                        <div className="dashboard-stat-card">
                            <span className="dashboard-stat-num">{stats.totalGenerations}</span>
                            <span className="dashboard-stat-label">Total Generations</span>
                        </div>
                        <div className="dashboard-stat-card dashboard-stat-accent">
                            <span className="dashboard-stat-num">{(stats.creditsTotal - stats.creditsUsed).toLocaleString()}</span>
                            <span className="dashboard-stat-label">Credits Available</span>
                        </div>
                        <div className="dashboard-stat-card dashboard-stat-success">
                            <span className="dashboard-stat-num">{stats.activeAutomations}</span>
                            <span className="dashboard-stat-label">Active Automations</span>
                        </div>
                    </div>
                </div>
            </header>

            {/* AI Command Center */}
            <section className="dashboard-section">
                <button className="ai-command-card" onClick={() => onNavigate('chat')}>
                    <div className="ai-command-glow"></div>
                    <div className="ai-command-content">
                        <div className="ai-command-icon-wrap">
                            <span className="ai-command-icon"><ChatBotIcon size={28} /></span>
                            <div className="ai-command-ring"></div>
                        </div>
                        <div className="ai-command-text">
                            <div className="ai-command-header">
                                <h2 className="ai-command-title">AI Command Center</h2>
                                <span className="ai-status-live">
                                    <span className="ai-status-dot"></span>
                                    Live
                                </span>
                            </div>
                            <p className="ai-command-desc">
                                Tell our AI what you need in plain English. It will analyze your business,
                                strategize the best approach, and execute automatically.
                            </p>
                            <div className="ai-command-features">
                                <span><CheckIcon size={12} /> Natural Language</span>
                                <span><CheckIcon size={12} /> Auto-Execute</span>
                                <span><CheckIcon size={12} /> Real-time Results</span>
                            </div>
                        </div>
                        <span className="ai-command-arrow"><ArrowRightIcon size={20} /></span>
                    </div>
                </button>
            </section>

            {/* Competitor Intelligence Scanner */}
            <CompetitorScannerSection />

            {/* Your Reports Section */}
            <section className="dashboard-section">
                <div className="section-header">
                    <div className="section-title-wrap">
                        <span className="section-icon"><BarChartIcon size={20} /></span>
                        <div>
                            <h2 className="section-title">Your Reports</h2>
                            <p className="section-subtitle">Auto-generated insights ready to view</p>
                        </div>
                    </div>
                    <span className="section-badge-ready"><CheckIcon size={12} /> Ready</span>
                </div>
                <div className="premium-grid">
                    {autoGeneratedReports.map((report, i) => renderAutoGeneratedCard(report, i))}
                </div>
            </section>

            {/* Strategy & Content Section */}
            <section className="dashboard-section">
                <div className="section-header">
                    <div className="section-title-wrap">
                        <span className="section-icon"><TargetIcon size={20} /></span>
                        <div>
                            <h2 className="section-title">Strategy & Content</h2>
                            <p className="section-subtitle">Generate your marketing plan & content calendar together</p>
                        </div>
                    </div>
                    {linkedGenerated ? (
                        <span className="section-badge-ready"><CheckIcon size={12} /> Generated</span>
                    ) : linkedLoading ? (
                        <span className="section-badge-loading">
                            <span className="badge-spinner"></span>
                            Generating...
                        </span>
                    ) : (
                        <span className="section-count">2 tools</span>
                    )}
                </div>
                <div className="premium-grid premium-grid-linked">
                    {linkedReports.map((report, i) => renderLinkedCard(report, i))}
                </div>

                {/* Info Banner */}
                <div className="info-banner">
                    <span className="info-banner-icon"><BoltIcon size={16} /></span>
                    <p className="info-banner-text">
                        <strong>Smart Generation:</strong> These two reports are generated together using the same AI analysis for cohesive strategy.
                    </p>
                </div>
            </section>

            {/* Strategy & Planning */}
            <section className="dashboard-section">
                <div className="section-header">
                    <div className="section-title-wrap">
                        <span className="section-icon"><RocketIcon size={20} /></span>
                        <div>
                            <h2 className="section-title">Strategy & Planning</h2>
                            <p className="section-subtitle">Build your marketing foundation</p>
                        </div>
                    </div>
                    <span className="section-count">{strategyTools.length} tools</span>
                </div>
                <div className="premium-grid">
                    {strategyTools.map((tool, i) => renderGeneratorCard(tool, i, 0))}
                </div>
            </section>

            {/* Research & Analysis */}
            <section className="dashboard-section">
                <div className="section-header">
                    <div className="section-title-wrap">
                        <span className="section-icon"><SearchIcon size={20} /></span>
                        <div>
                            <h2 className="section-title">Research & Analysis</h2>
                            <p className="section-subtitle">Data-driven market insights</p>
                        </div>
                    </div>
                    <span className="section-count">{researchTools.length} tools</span>
                </div>
                <div className="premium-grid">
                    {researchTools.map((tool, i) => renderGeneratorCard(tool, i, 1))}
                </div>
            </section>

            {/* Content Creation */}
            <section className="dashboard-section">
                <div className="section-header">
                    <div className="section-title-wrap">
                        <span className="section-icon"><PencilIcon size={20} /></span>
                        <div>
                            <h2 className="section-title">Content Creation</h2>
                            <p className="section-subtitle">Create engaging content at scale</p>
                        </div>
                    </div>
                    <span className="section-count">{contentTools.length} tools</span>
                </div>
                <div className="premium-grid">
                    {contentTools.map((tool, i) => renderGeneratorCard(tool, i, 2))}
                </div>
            </section>

            {/* Ads & Outreach */}
            <section className="dashboard-section">
                <div className="section-header">
                    <div className="section-title-wrap">
                        <span className="section-icon"><MegaphoneIcon size={20} /></span>
                        <div>
                            <h2 className="section-title">Ads & Outreach</h2>
                            <p className="section-subtitle">Reach and convert your audience</p>
                        </div>
                    </div>
                    <span className="section-count">{adTools.length} tools</span>
                </div>
                <div className="premium-grid">
                    {adTools.map((tool, i) => renderGeneratorCard(tool, i, 3))}
                </div>
            </section>

            {/* Coming Soon */}
            <section className="dashboard-section dashboard-section-muted">
                <div className="section-header">
                    <div className="section-title-wrap">
                        <span className="section-icon"><ConstructionIcon size={20} /></span>
                        <div>
                            <h2 className="section-title">Coming Soon</h2>
                            <p className="section-subtitle">New tools in development</p>
                        </div>
                    </div>
                    <span className="section-badge-dev">In Development</span>
                </div>
                <div className="coming-soon-grid">
                    {comingSoon.map((item, i) => (
                        <div key={item.id} className="coming-soon-card">
                            <span className="coming-soon-icon">{TOOL_ICONS[item.id]}</span>
                            <div className="coming-soon-info">
                                <h4 className="coming-soon-title">{item.title}</h4>
                                <p className="coming-soon-desc">{item.description}</p>
                            </div>
                            <span className="coming-soon-eta">{item.eta}</span>
                        </div>
                    ))}
                </div>
            </section>
        </div>
    )
}

export default Dashboard
